version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: local-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-lol
      POSTGRES_DB: mode
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
